var sampleResponse = {
ETH_GNO:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 1,
   newTrade: 0,
   orderBookRemove: 1,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 5.61641539 },
ETH_GNT:
 { orderBookModify_BIDS: 1,
   orderBookModify_ASKS: 1,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 16773.13717827,
   askChanges: 0.13925578 },
ETH_LSK:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
ETH_REP:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
ETH_STEEM:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
ETH_ZEC:
 { orderBookModify_BIDS: 1,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 1,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 188.29,
   askChanges: 0 },
USDT_BTC:
 { orderBookModify_BIDS: 2,
   orderBookModify_ASKS: 0,
   newTrade: 1,
   orderBookRemove: 1,
   buyVolume: 0,
   sellVolume: 0.05634041,
   bidChanges: 5.4515154,
   askChanges: 0 },
USDT_DASH:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
USDT_ETC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
USDT_ETH:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
USDT_LTC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 1,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0.00326122 },
USDT_NXT:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
USDT_REP:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
USDT_STR:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 2,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 115341.98020876 },
USDT_XMR:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
USDT_XRP:
 { orderBookModify_BIDS: 1,
   orderBookModify_ASKS: 0,
   newTrade: 1,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 3302.43736419,
   bidChanges: 23095.23663928,
   askChanges: 0 },
USDT_ZEC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
XMR_BCN:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
XMR_BLK:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
XMR_BTCD:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
XMR_DASH:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
XMR_LTC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
XMR_MAID:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
XMR_NXT:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
XMR_ZEC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 } }
Order Pairs:  { BTC_AMP:
 { orderBookModify_BIDS: 1,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 82.97110841,
   askChanges: 0 },
BTC_ARDR:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_BCN:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 1,
   newTrade: 1,
   orderBookRemove: 0,
   buyVolume: 0.00201316,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 934974.52796771 },
BTC_BCY:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_BELA:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_BLK:
 { orderBookModify_BIDS: 1,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 1,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 34692,
   askChanges: 0 },
BTC_BTCD:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_BTM:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_BTS:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 1,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_BURST:
 { orderBookModify_BIDS: 1,
   orderBookModify_ASKS: 1,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 21854.41614439,
   askChanges: 23630.56025991 },
BTC_CLAM:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_DASH:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_DCR:
 { orderBookModify_BIDS: 1,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0.89931272,
   askChanges: 0 },
BTC_DGB:
 { orderBookModify_BIDS: 2,
   orderBookModify_ASKS: 5,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 284947.64130727004,
   askChanges: 10741285.341841381 },
BTC_DOGE:
 { orderBookModify_BIDS: 1,
   orderBookModify_ASKS: 4,
   newTrade: 4,
   orderBookRemove: 1,
   buyVolume: 0.50904079,
   sellVolume: 0,
   bidChanges: 5898895.95232209,
   askChanges: 46538462.66950005 },
BTC_EMC2:
 { orderBookModify_BIDS: 1,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 12903.22580646,
   askChanges: 0 },
BTC_ETC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_ETH:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 1,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_EXP:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_FCT:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 1,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_FLDC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_FLO:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_GAME:
 { orderBookModify_BIDS: 1,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 1,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 759.44282413,
   askChanges: 0 },
BTC_GNO:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_GNT:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_GRC:
 { orderBookModify_BIDS: 1,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 15688.71901358,
   askChanges: 0 },
BTC_HUC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_LBC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_LSK:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_LTC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 1,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_MAID:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_NAUT:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_NAV:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_NEOS:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_NMC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_NOTE:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_NXC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_NXT:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_OMNI:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_PASC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_PINK:
 { orderBookModify_BIDS: 2,
   orderBookModify_ASKS: 1,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 42803.37467931,
   askChanges: 9746.07734927 },
BTC_POT:
 { orderBookModify_BIDS: 1,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 215.88855869,
   askChanges: 0 },
BTC_PPC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_RADS:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_REP:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 1,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 166.66805556 },
BTC_RIC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_SBD:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_SC:
 { orderBookModify_BIDS: 2,
   orderBookModify_ASKS: 1,
   newTrade: 1,
   orderBookRemove: 0,
   buyVolume: 0.25070033,
   sellVolume: 0,
   bidChanges: 3122645.99823399,
   askChanges: 240138.20061965 },
BTC_SJCX:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_STEEM:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_STR:
 { orderBookModify_BIDS: 2,
   orderBookModify_ASKS: 1,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 11439.57742356,
   askChanges: 16980.08924161 },
BTC_STRAT:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_SYS:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 2,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 1237056.14441456 },
BTC_VIA:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 1,
   newTrade: 0,
   orderBookRemove: 1,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 96.19452945 },
BTC_VRC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_VTC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_XBC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_XCP:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_XEM:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_XMR:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 1,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 1.89222741 },
BTC_XPM:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 1,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0.9985006 },
BTC_XRP:
 { orderBookModify_BIDS: 1,
   orderBookModify_ASKS: 1,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 134.47186176,
   askChanges: 18564.54442367 },
BTC_XVC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
BTC_ZEC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
ETH_ETC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
ETH_GNO:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
ETH_GNT:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
ETH_LSK:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
ETH_REP:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
ETH_STEEM:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
ETH_ZEC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
USDT_BTC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 1,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0.5 },
USDT_DASH:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
USDT_ETC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
USDT_ETH:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
USDT_LTC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 1,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
USDT_NXT:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
USDT_REP:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
USDT_STR:
 { orderBookModify_BIDS: 1,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 88.0057028,
   askChanges: 0 },
USDT_XMR:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
USDT_XRP:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
USDT_ZEC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
XMR_BCN:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
XMR_BLK:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
XMR_BTCD:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
XMR_DASH:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
XMR_LTC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
XMR_MAID:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
XMR_NXT:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 },
XMR_ZEC:
 { orderBookModify_BIDS: 0,
   orderBookModify_ASKS: 0,
   newTrade: 0,
   orderBookRemove: 0,
   buyVolume: 0,
   sellVolume: 0,
   bidChanges: 0,
   askChanges: 0 }
};
module.exports = sampleResponse;